// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI8QTvuFfiJEJgwr1tgQ5qhbhmtwBVNJs',
    appId: '1:216892485040:web:671928c4d4c8a1eb477a75',
    messagingSenderId: '216892485040',
    projectId: 'authenticate-fc5c5',
    authDomain: 'authenticate-fc5c5.firebaseapp.com',
    storageBucket: 'authenticate-fc5c5.appspot.com',
    measurementId: 'G-2FBJLC34SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCo5rCp6Pvor6gtFon-F-7N5vAkV0KYWs',
    appId: '1:216892485040:android:2d18bab73d3ec856477a75',
    messagingSenderId: '216892485040',
    projectId: 'authenticate-fc5c5',
    storageBucket: 'authenticate-fc5c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPV5gWPViHot6pKL-AmSV9qZ71m8sk0uk',
    appId: '1:216892485040:ios:85883f8a018664bb477a75',
    messagingSenderId: '216892485040',
    projectId: 'authenticate-fc5c5',
    storageBucket: 'authenticate-fc5c5.appspot.com',
    iosClientId: '216892485040-0vn046hg3o48nnccqg1lru2oeihf7hm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPV5gWPViHot6pKL-AmSV9qZ71m8sk0uk',
    appId: '1:216892485040:ios:85883f8a018664bb477a75',
    messagingSenderId: '216892485040',
    projectId: 'authenticate-fc5c5',
    storageBucket: 'authenticate-fc5c5.appspot.com',
    iosClientId: '216892485040-0vn046hg3o48nnccqg1lru2oeihf7hm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticate',
  );
}
